### ISSUE TITLE
Core documentation

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#1]
Migrated from https://github.com/SAFE-Stack/SAFE-Stack.github.io/issues/11

- [x] Introduction
   - [x] Why SAFE?
- [x] Getting up and running
   - [x] Quick start
   - [x] SAFE Dojo
   - [x] Example repositories
   - [x] Feedback & Testimonials
   - [x] Support and Training
- [x] SAFE Stack overview
   - [x] Server Side programming in SAFE
   - [x] Cloud Platform - Azure (AWS + GCP to come?)
   - [x] Fable
   - [x] Elmish
- [ ] Mobile SAFE

**Comment by kunjee17** [comment]
@isaacabraham can you please add place for build with SAFE stack. It will contain production application that are built with SAFE or spin off SAFE stack...

**Comment by isaacabraham** [comment]
@kunjee17 could that be the testimonials page? or something else?

**Comment by isaacabraham** [comment]
@alfonsogarciacaro @Krzysztof-Cieslak @mangelmaxime I've created placeholder pages in the SAFE docs for more details of what Fable, Saturn and Elmish are, and specifically how they fit into SAFE. 

As the maintainers of Fable, Saturn and Elmish, this is an opportunity for you to add whatever you would like on the SAFE site directly. This shouldn't be a replacement for docs on those sites, but should provide more details on the value proposition of the technologies, how it makes end-to-end web programming easier, what the overall benefits are etc. - and then link to the real site for more details.

Hopefully, you're interested in doing this, but if you're not (or just don't have the time), let me know and we'll make them up-for-grabs for someone else to write about them.

**Comment by alfonsogarciacaro** [comment]
I don't have a lot of time atm, but I'll try to write a quick summary and link to Fable site :+1:

**Comment by forki** [comment]
That's the spirit. No need for details, we only need to explain why we
think it's a particularly good fit for the stack.

Alfonso Garcia-Caro <notifications@github.com> schrieb am Di., 17. Apr.
2018, 22:40:

**Comment by Krzysztof-Cieslak** [comment]
What's free time?

**Comment by kunjee17** [comment]
I ll also add all SAFE stack links from awesome-fable to here...

**Comment by isaacabraham** [comment]
Short capture of HMR in action.

![hmr](https://user-images.githubusercontent.com/1781813/39061043-5aa3737e-44c3-11e8-9789-029b285f180c.gif)

**Comment by kunjee17** [comment]
@isaacabraham HMR may be the best thing happened to Fable.... I guess we should be thanking @MangelMaxime if I am forgetting...

**Comment by isaacabraham** [comment]
@MangelMaxime I've done the Elmish one now I think but obviously feel free to add more! I've also done Azure and Saturn - @Krzysztof-Cieslak please feel free to review / change and will done another one on Fable in the next days.

**Comment by isaacabraham** [comment]
@kunjee17 that will be great. Feel free to add in the learnin resources section.

**Comment by isaacabraham** [comment]
@forki would you be interested / able to write a short page on Mobile SAFE i.e. SAFE on React Native?

**Comment by forki** [comment]
yeah one day - not today ;-)

**Comment by kunjee17** [comment]
@isaacabraham did moved links related to SAFE from awesome-fable to safe learning resources. Sorry for delay.

**Comment by isaacabraham** [comment]
I'm closing this issue . I think we have all the basics covered - perhaps mobile safe is something for another day. Especially now that there's Fabulous which is another way of writing such apps (or perhaps they are SAE apps ;-)
