### ISSUE TITLE
Link to Fulma is wrong

### ISSUE THREAD

**Issue by projecteon** [SAFE-Stack/docs#101]
Currently links to a 404 page since Fulma moved repos:
https://mangelmaxime.github.io/Fulma

Should link to:
https://fulma.github.io/Fulma/

**Comment by isaacabraham** [comment]
Thanks for pointing this out. Would you consider submitting a PR with a fix for this? 😁

**Comment by projecteon** [comment]
Hmm seems its updated but not published. Sorry.
