### ISSUE TITLE
Inconsistency in SAFE's "S"

### ISSUE THREAD

**Issue by breyed** [SAFE-Stack/docs#105]
If you start at https://safe-stack.github.io/ and click Read the Documentation, and click Next two times, you end up on at [SAFE Stack components](https://safe-stack.github.io/docs/overview/), which tells you "S" is for Saturn.

But if you go back to https://safe-stack.github.io/ and click Read More About Safe, you end up at an [announcement](https://compositional-it.com/blog/2017/09-22-safe-release/index.html), which says that "S" is for Suave.

My guess is that the confusion is caused by an announcement that has become out of date. Either it should be updated, or the Read More About Safe link should point to a living page, rather than a fixed blog post.

**Comment by isaacabraham** [comment]
@breyed see https://safe-stack.github.io/docs/news/ for the background behind this. But yes, we're planning on updating that announcement page now as it's out of date and should explain this.

**Comment by isaacabraham** [comment]
Closing as documentation is updated now.

**Comment by breyed** [comment]
It's better, but the Saturn link in the [announcement](https://compositional-it.com/blog/2017/09-22-safe-release/index.html) still brings you to a page about Suave.

**Comment by isaacabraham** [comment]
@breyed yes, the main intro page has been updated but the next one down hasn't been. That's a bit more work that @Krzysztof-Cieslak will be doing at some point (I think!).

**Comment by breyed** [comment]
Sounds good, though it's common to keep a GitHub issue open while there's still work to do, so that tracking stays robust. The issue can be assigned to the person who will be doing the work.
