### ISSUE TITLE
Yarn required?

### ISSUE THREAD

**Issue by NatElkins** [SAFE-Stack/docs#108]
I've installed the most recent version of the SAFE stack template, and tried to follow the instructions from the quick start: https://safe-stack.github.io/docs/quickstart/

I have npm installed, but not yarn.  When I tried to run `fake build --target run`, I received the following error:

```
Script reported an error:
-> yarn was not found in path. Please install it and make sure it's available from your path. See https://safe-stack.github.io/docs/quickstart/#install-pre-requisites for more info
```

After I installed yarn, it worked without issue.  Should the language be changed to require yarn, instead of "yarn or npm"?  If so, I'm happy to submit a PR.

**Comment by theimowski** [comment]
Yes yarn is a prerequisite to run SAFE template with default configuration.
See also https://github.com/SAFE-Stack/docs/pull/106

**Comment by isaacabraham** [comment]
Obsolete with SAFE 2
