### ISSUE TITLE
Add instructions on how to add packages

### ISSUE THREAD

**Issue by MarcCoquand** [SAFE-Stack/docs#111]
Hello,

As a newcomer to dotnet and F# ecosystem it would be very helpful if you added instructions on how to add dependencies to the project. Simply typing `paket add PACKAGE`, which is the instructions on nuget, is not enough. You have to do `paket add PACKAGE --project Server/Server.fsproj` for backend dependencies and `paket add PACKAGE --project Client/Client.fsproj` for frontend.

**Comment by isaacabraham** [comment]
Fixed with the latest recipes e.g. https://safe-stack.github.io/docs/recipes/package-management/add-nuget-package-to-server/
