### ISSUE TITLE
Update documentation on registering an app on Azure for deployment

### ISSUE THREAD

**Issue by bruinbrown** [SAFE-Stack/docs#118]
cc @isaacabraham

Currently the documentation uses the legacy application registration within Azure AD but there is no mention that you should use the legacy creation flow. We have 2 options for how to fix this

1. We can change the wording to refer to ``App Registration (Legacy)``
2. We can look into how to use the new App Registration, this would likely need some changes
    - Screenshots will need updating
    - The new app registration has got rid of the idea of native apps and so we'd need to change this
    - A new app registration will by default only be available to users in the same tenant. If no tenant is supplied in the authenticate device function then an error is returned (AADSTS50059)

**Comment by isaacabraham** [comment]
I believe that the new app registration page lets you specify what tenant its usable in at the time of creation of the app registration itself?

If native apps aren't available anymore, what's the alternative?

**Comment by isaacabraham** [comment]
Closing - obsolete.
