### ISSUE TITLE
Document interacting between client and server: return unit 

### ISSUE THREAD

**Issue by selketjah** [SAFE-Stack/docs#124]
When you return a unit from the server, Thoth.Json gives you this error:
`Cannot generate auto decoder for Microsoft.FSharp.Core.Unit. Please pass an extra decoder.`

There are a couple of known workarounds, it would be nice to have these known exceptions documenten somewhere.

**Comment by isaacabraham** [comment]
This is something that catches lots of people out - the resulting type should be `obj` (or can simply be the generic `_`) which then works. Let's add a page with a few of these ideas.

**Comment by isaacabraham** [comment]
@selketjah do you think that this would have been both obvious, useful and findable to you?
