### ISSUE TITLE
Update 'Handling "unit" calls' section

### ISSUE THREAD

**Issue by MangelMaxime** [SAFE-Stack/docs#136]
On [this page](https://safe-stack.github.io/docs/feature-clientserver-serialization/), there is a section dedicated to `Handling "unit" calls`.

Today, I released a new versions of Thoth.Json(.Net) which add support for `unit`. Could someone from the SAFE stack test it and see if it's working correctly?

If yes, then we should add a mention that since `Thoth.Json 3.4.0` and `Thoth.Json.Net 3.6.0` users can now use `unit` in their server response.

**Comment by theimowski** [comment]
Thanks @MangelMaxime - when https://github.com/SAFE-Stack/SAFE-template/pull/318 is ready I'll update the Thoth.Json dependencies to latest, test them and then when template ships with latest Thoth.Json we can add a note on that in docs :+1:

**Comment by isaacabraham** [comment]
@theimowski @MangelMaxime I think that we can close this, right?

**Comment by MangelMaxime** [comment]
Hello @isaacabraham,

not yet the documentation still need an update because it says that unit is not supported by Thoth.Json while it is now.

**Comment by teknikal-wizard** [comment]
@isaacabraham  I've removed that bit in [this PR](https://github.com/SAFE-Stack/docs/pull/265/commits/616e056334e5551256c6db95d882c8b1ae8efc07) so I guess this can be closed once merged?
