### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#148]
I've been looking at giving the website a refresh. I think that we have a few options:

1. Do nothing.
2. Keep the site theme and tech (mkdocs) the same. Create a new static landing page, or simply incorporate it onto the docs home page.
3. Migrate the site to a new tech e.g. hugo learn? Create a new static landing page, or simply incorporate it onto the docs home page.
4. Create a new site that has a proper landing page and also a documentation area in it. I'm thinking of something along the lines of the actual Hugo site https://gohugo.io/, which has a proper landing page but integrated docs site with full search.

Keeping the site is the cheapest option but we're going to need to add / remove a lot of content anyway once v2 of the template drops. I strongly think that the current landing page should be replaced, although this could just be a static page that we chuck in as a one-off.

What do people think? Is anyone available to support with this?

**Comment by panesofglass** [comment]
I'm tentatively available to help. :)

**Comment by Krzysztof-Cieslak** [comment]
5. Migrate to Fornax ;-)

**Comment by robertpi** [comment]
Happy to help out. I think the main problems with the landing page are:

- Annoying animation, that delays you seeing the content
-  doesn't easily allow you to click though to the main docs / quick start / github repo.

Other than the design is quite nice and could be tweaked to solve those problems. I find the design and layout of the docs themselves quite good too.

Don't know mkdocs. Hugo is a solid choice, Fornax would mean quite a bit more work, in my opinion, but would drive improvements to that project.

**Comment by Krzysztof-Cieslak** [comment]
> Fornax would mean quite a bit more work

Bear in mind that we already have a fairly good documentation template for Fornax, that's defined in Waypoint - it's based on Hugo learn, I'm using it currently for Ionide webpage (https://ionide.io/)

**Comment by isaacabraham** [comment]
OK, let's keep this discussion going. Perhaps the best way is to talk about the outcomes that we should need, regardless or hugo, mkdocs, fornax, whatever:

* Documentation should be easy to update - ideally markdown, I suppose.
* Documentation should be hierarchical in nature
* Documentation must be searchable
* Ability to create or host some kind of landing page that may or may not share the same theme as the documentation (preference is for the whole site to be one).
* Ability to break out to raw HTML if needed.
* Ability to host images and embed videos e.g. YouTube videos.
* Theme must look attractive and professional

* Landing page could support some sort of banner / recent content / news e.g. "New version of SAFE template launched" or "New guide available: Working with websockets" etc.

The content will be mostly similar to the existing site except I see several additions:

* Recipes - step by step guides for carrying out common tasks
* Libraries - list of SAFE-recommended libraries and packages
* Perhaps, in time, a blog section.

**Comment by Krzysztof-Cieslak** [comment]
Just FYI, https://saturnframework.org is all ported to Fornax. Landing page is still plain HTML, I’ve seen no point in porting it, but the documentation and api ref is generated. Additionally it’s all searchable.

**Comment by panesofglass** [comment]
@Krzysztof-Cieslak seems like a good approach. Do you have theme support in Fornax yet?

**Comment by robertpi** [comment]
Yes and no. The look and feel comes from the code "generators" folder, so creating a new theme is simply swapping this for code that renders the posts differently. 

I think it would be good if we could make changing the look and feel easier, but haven't spent too much time thinking about how it could be done. Maybe @Krzysztof-Cieslak already has?

**Comment by demirtas-dev** [comment]
Hi everyone! Just an update to where we are at the moment with this issue.

Most likely, we will have a seperate landing page and a docs page, each based on two different themes. We we will make slight adjustments to colors, and possibly the layout, to maintain consistency between them.

We are considering a few different themes which I will list below but the one we favour as the landing page at the moment is [Hugo Fresh](https://themes.gohugo.io/hugo-fresh/). If we go with this, a good option for a docs page seems to be [Hugo Whisper](https://themes.gohugo.io//theme/hugo-whisper-theme/). 

What do you guys think?

### Some other options we're looking at:

#### Landing Pages:
- [Firsco](https://jamstackthemes.dev/theme/jekyll-frisco/)
- [Saastec 4](http://quomodosoft.com/html/saastec/saastec/home-4.html)
- [Aeroland](https://demo.hasthemes.com/aeroland-preview/index-app-landing.html)
- [Bootsland](http://themeht.com/bootsland/html/index.html)
- [Bootsland2](http://themeht.com/bootsland/html/index-2.html)
- [Landrick SaaS](http://landrick.react.themesbrand.com/index)
- [Saasmax](http://quomodosoft.com/html/saastec/saastec/home-7.html)

#### Docs:
- [Docsy](https://www.docsy.dev/docs/getting-started/)
- [Learn](https://themes.gohugo.io/theme/hugo-theme-learn)
