### ISSUE TITLE
mkdocs serve issue

### ISSUE THREAD

**Issue by Pipsy100** [SAFE-Stack/docs#149]
C:\C#Projects\SAFE-Stack\docs\docs>mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - template-webpack.md

I am getting this error while running mkdocs serve command. Anybody knows why?

**Comment by theimowski** [comment]
is that a warning or error? If warning then the message makes sense - probably the document hasn't been added to the menu

**Comment by Pipsy100** [comment]
No Thomas, it is an error.

Van: Tomasz Heimowski <notifications@github.com>
Verzonden: maandag 27 april 2020 20:31
Aan: SAFE-Stack/docs <docs@noreply.github.com>
CC: Pipsy100 <w_hoogland@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SAFE-Stack/docs] mkdocs serve issue (#149)


is that a warning or error? If warning then the message makes sense - probably the document hasn't been added to the menu

**Comment by theimowski** [comment]
That `template-webpack.md` file has been once added as a draft but never really got attention - removed it now, can you try with latest master?
