### ISSUE TITLE
Fix automatic CI docs build

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/docs#153]
I've just realised that for a long time now the travis builds are actually failing https://travis-ci.com/github/SAFE-Stack/docs/builds

**Comment by isaacabraham** [comment]
Almost there! The original error about SVG is gone but this is now in its place

```
1.38s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
invalid option "--token="
failed to deploy
```

**Comment by theimowski** [comment]
is this from your local console? Travis works fine: https://travis-ci.org/github/SAFE-Stack/docs

**Comment by isaacabraham** [comment]
Doh. No idea what I was looking at!
