### ISSUE TITLE
Docs build is broken

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#155]
@theimowski I've had a look, seems that it happened a month ago or so... any idea what happened? I can't figure it out, something about a missing svg icon?

**Comment by theimowski** [comment]
Haven't looked yet, but spotted that in #153

**Comment by theimowski** [comment]
Fixed now, was due to breaking change in MkDocs material https://squidfunk.github.io/mkdocs-material/releases/5/#extrasocial

For reference the error was:
`jinja2.exceptions.TemplateNotFound: .icons/.svg`
