### ISSUE TITLE
broken links on template-overview.md (elmish.streams)

### ISSUE THREAD

**Issue by ajeckmans** [SAFE-Stack/docs#158]
There are a few broken links to a library called Elmish.Streams in the template overview page. I cant find any documentation or source of this library. Could it have been renamed to Fable.Reaction?

**Comment by isaacabraham** [comment]
Can this be closed now?

**Comment by theimowski** [comment]
The problem is still there, but it's in the "Legacy v1 SAFE Template" section, which I want to treat as a read-only archive for a couple more months since v2 has been already released

**Comment by ajeckmans** [comment]
@theimowski  We're over 20 months past your last comment. I guess it can be closed now?
