### ISSUE TITLE
Broken links in feature-clientserver-bridge.md

### ISSUE THREAD

**Issue by Kinrany** [SAFE-Stack/docs#165]
On the website: https://safe-stack.github.io/docs/feature-clientserver-bridge/

In the second paragraph the links "stateful APIs in Saturn" and "model-view-update pattern" are broken both on the website and in the Markdown source.

The website links are pointing to sub-resources (e.g. `docs/feature-clientserver-bridge/component-saturn`) instead of resources on the same level (e.g. `docs/component-saturn`).

The Markdown links don't work without the `.md` extension.

The previous commit seems to also be about broken links: https://github.com/SAFE-Stack/docs/commit/9edaf1538e0083642b954926a135cef5602a9b95

And this other issue: https://github.com/SAFE-Stack/docs/issues/158

**Comment by theimowski** [comment]
Thanks for reporting that - are you willing to create a PR that would fix it?

**Comment by Kinrany** [comment]
Sure! I don't really know how though

**Comment by theimowski** [comment]
How to fix the issue or how to contribute?

**Comment by Kinrany** [comment]
How to fix the issue. 

Is it important for markdown links to work? Otherwise, would it work to just append `../` to both links? 

I'm assuming there could be other similar problems with links, so we may want to check the history and see what else changed when these links broke

**Comment by theimowski** [comment]
I think it's enough to make sure the link has an `.md` extension. Have a look at other sections, e.g. https://github.com/SAFE-Stack/docs/blob/master/docs/faq-build.md where links work fine
