### ISSUE TITLE
Femto docs: should run inside Client rather than root directory 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [SAFE-Stack/docs#194]
Femto [docs](https://safe-stack.github.io/docs/recipes/package-management/sync-nuget-and-npm-packages/) mention that step 2 (analyse dependencies) should run in the root directory. That is not the case, you should either _be_ inside the Client directory to run `femto` or _point_ Femto to where the client directory is:
```bash
# Analyse dependencies
dotnet femto ./src/Client

# Resolve package requirements
dotnet femto ./src/Client --resolve
```
Please try it out locally to make sure it works too. 

I just published Femto v0.8.7 and it should work ootb when instrumenting locally installed paket 

Another thing to add if you working on the docs for Femto is to explain `femto install` because it abstracts nuget/paket and does automatic resolution of potentially required npm package (you can even use it for the Server project)

**Comment by TerenceHinrichsen** [comment]
Ran into this one today, tried to run in Root, and got an error, thought I missed something. Should be a simple docs update.
