### ISSUE TITLE
Travis not deploying latest SAFE-docs

### ISSUE THREAD

**Issue by Akash-Mair** [SAFE-Stack/docs#203]
Hey @theimowski!

It looks like for the last few merges into master the build has not been triggered since the `Owner SAFE-Stack does not have enough credits.`  
Before that there seems to be an error of `Abuse Detected` for the following PR - Added 'SQLProvider SQL Server SSDT' to the Data recipes

Resources:
- https://travis-ci.com/github/SAFE-Stack/docs/requests
- https://docs.travis-ci.com/user/billing-faq/
- https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191

If you need anything else please let me know :)

**Comment by theimowski** [comment]
Ouch indeed 🤦  
Seems like the build for SAFE-template is taking too many Travis credits.
I've mailed the Travis support team to ask for additional OSS credits as per https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source
Let's see what they say
FYI @isaacabraham

**Comment by isaacabraham** [comment]
@theimowski perhaps we could consider migrating to GitHub Actions (or Azure Dev Ops) - AFAIK both are free for OSS stuff.

**Comment by theimowski** [comment]
Ok we've been granted additional Travis credits for SAFE-Stack organization 🎉  
The docs plan is now unblocked and website is up to date with state of this repository 👍
