### ISSUE TITLE
Update dotnet tools advice

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#228]
From https://safe-stack.github.io/docs/quickstart/

> Enter dotnet tool restore to install local tools like FAKE.

We don't use the FAKE tool any more. I think just Paket is needed. FAKE as a dotnet tool should probably be removed.

Also the tool restore is only required once.

**Comment by olivercoad** [comment]
paket, fable, and fantomas

**Comment by isaacabraham** [comment]
Right. Maybe just updating the docs to mention one of those, and secondly removing FAKE-CLI (if not already done) from the template itself?
