### ISSUE TITLE
Tiny font for links in footer

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/docs#229]
Is it just me or are these navigation links (previous and next page) in footer barely visible? 

![image](https://user-images.githubusercontent.com/5909015/123861050-02459a80-d927-11eb-8f37-4e824bab7388.png)

**Comment by olivercoad** [comment]
Yep, didn't even know they were there. I don't think they really belong in the footer anyway. Maybe the left side-bar would be better?

**Comment by jwthomson** [comment]
The theme used by the docs is based on the material theme for mkdocs, but the footer in this repo had diverged somehow which is what caused the styling issues, which should now be resolved. @theimowski are you happy for this to be closed?
