### ISSUE TITLE
feature request for documentation: add test examples

### ISSUE THREAD

**Issue by draptik** [SAFE-Stack/docs#233]
As user of this framework I would like some guidance / best practices for writing tests.

What are typical integration or unit tests one might write (with examples in documentation)?

In C# one might consider using the `WebApplicationFactory<T>` approach.

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0

Is also reasonable here?

Don said it's ok to mention this tweet: https://twitter.com/dsymetweets/status/1417417949233795082

**Comment by isaacabraham** [comment]
I think it's probably out of scope for SAFE Stack really, but (appreciate this issue is 18 months old...) were you think client or server side or anything in particular?

**Comment by martinbryant** [comment]
@draptik I will close this but feel free to raise another issue with any specifics in response to the previous question
