### ISSUE TITLE
"Serve a file from the back-end" example not working

### ISSUE THREAD

**Issue by reigam** [SAFE-Stack/docs#237]
I tried using the "Serve a file from the back-end"example (with an out of the box standard template) and provided the xlsx file on the server.

First I got the error: 
```
    | DownloadFile ->
        model, Cmd.OfAsync.perform downloadFile () FileDownloaded

This expression was expected to have type
    'unit -> Msg'    
but here has type
    'Msg'    
```
changing _FileDownloaded_ to _FileDownloaded of unit_ 'solved' that problem, but when I try to download the file, nothing happens. 

npm shows the following output:
```
server: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
server:       Request starting HTTP/1.1 GET http://localhost:8085/api/IFileApi/download application/json;+charset=utf-8 -
server: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
server:       Request finished HTTP/1.1 GET http://localhost:8085/api/IFileApi/download application/json;+charset=utf-8 - - 404 0 - 1.5959ms
```

**Comment by isaacabraham** [comment]
@Akash-Mair is this one of your recipes?

**Comment by Akash-Mair** [comment]
I did the review so I'll take a look 😊

**Comment by Akash-Mair** [comment]
@reigam you're right that the `FileDownloaded` Msg needed to be of unit and I also noticed that the on click is PascalCased when it shouldn't be.
But I was able to get the file to download once I fixed those. Would you be able to share a sample repo?

**Comment by reigam** [comment]
@Akash-Mair thanks for the fast reply. 
I got it working by changing "~/files/file.xlsx" to "./files/file.xlsx".

This is probably a silly beginners question, but I couldn't figure out where ~ is pointing to. I tried creating an empty file 
```
        let writeArry = System.IO.File.WriteAllBytes("~/files/file.xlsx", [||])
        writeArry
```
, but this still didn't work.

**Comment by Akash-Mair** [comment]
Ahh I thought that the use of `~` meant substitute a valid file path but that's an assumption on my part and is worth changing to something that makes that more clearer or even having a note below.
I'll get that changed as it seems some of this recipe is due for an update! 

Thanks for raising this @reigam 😁

**Comment by reigam** [comment]
@Akash-Mair 
Well, that explains it :grimacing:
"In an ASP.NET application the framework controls recognise a tilde ('~') as a shortcut to the root of the application's virtual directory." 
I thought I was missing something. 

Thanks again, I much appreciate the help.
