### ISSUE TITLE
Upgrade upload/download binary content recipes to use latest Fable Remoting capabilities.

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#239]
See [here](https://github.com/SAFE-Stack/docs/pull/238#issuecomment-895230418).

**Comment by Zaid-Ajaj** [comment]
One more thing about the serving file recipe, there is this snippet
```fs
open System // We need this for the `Byte` type

type IFileAPI =
    { //...other routes 
      download : unit -> Async<Byte[]> }
```
Can be simplified to
```fs
type IFileAPI =
    { //...other routes 
      download : unit -> Async<byte[]> }
```
The type abbreviation `byte` doesn't need a namespace.

**Comment by OtagIt** [comment]
Unfortunately, there is also missing example how to handle uploading of file on the server (saturn) side.

Invalid link with text **send the file from the client to the server** in _upload-file-from-client.md_ ("Upload file from the client")

It would be great to have complete example there.
