### ISSUE TITLE
Broken links on "Package my SAFE app for deployment"

### ISSUE THREAD

**Issue by reigam** [SAFE-Stack/docs#242]
On the site ["Package my SAFE app for deployment"](https://safe-stack.github.io/docs/recipes/build/bundle-app/), 
the first two links:

- "different port" (linking to https://safe-stack.github.io/faq-build) 
- "here" (linking to https://safe-stack.github.io/template-safe-commands) 

do not work.

**Comment by theimowski** [comment]
thanks!
