### ISSUE TITLE
Feature request for documentation: add hosting "how do I"'s

### ISSUE THREAD

**Issue by reigam** [SAFE-Stack/docs#243]
Looks like there were [examples ](https://github.com/SAFE-Stack/docs/issues/154) for how to use different hosting services in an older version of these docs (for SAFE v1).  Are there any plans to update these for v3 in the near future?

**Comment by isaacabraham** [comment]
@reigam Yes for docs - but we will most likely focus on just Docker for the flexibility that that gives in terms of portability.
