### ISSUE TITLE
Debug instructions for VS Code incorrect

### ISSUE THREAD

**Issue by matthewcrews** [SAFE-Stack/docs#244]
The instructions on the Debug page state that you should install the `Debugger for Chrome` extension into VS Code. This extension has been deprecated because the functionality is now built into VS Code.

Debug Page: https://safe-stack.github.io/docs/recipes/developing-and-testing/debug-safe-app/

Section in question
![image](https://user-images.githubusercontent.com/1593215/138133443-4ac4f433-ed49-4843-975a-c545947661a4.png)

**Comment by isaacabraham** [comment]
Closing as PR has merged in AFAICS.
