### ISSUE TITLE
Add IE11 support recipe

### ISSUE THREAD

**Issue by mattgallagher92** [SAFE-Stack/docs#245]
Babel is no longer part of the default template from `dotnet new safe`. This made npm and webpack maintenance easier, but means that the client is no longer compatible with Internet Explorer. Add a recipe that explains how to add IE11 support back.

Relates to https://github.com/SAFE-Stack/SAFE-template/pull/415#issuecomment-851579254.

**Comment by mattgallagher92** [comment]
Kevin Frey has provided some information to help:

- [Minimal repo updated to work with IE11](https://github.com/Freymaurer/SAFE-MinExcel)
- Relevant part of [package.json](https://github.com/Freymaurer/SAFE-MinExcel/blob/b87b597d70cba6484dd95ba3b59395ecfcba31ad/package.json#L9-L11):
  ```json
        "@babel/core": "^7.16.0",
        "@babel/preset-env": "^7.16.0",
        "babel-loader": "^8.2.3",
  ```
- [webpack.config.js CONFIG](https://github.com/Freymaurer/SAFE-MinExcel/blob/b87b597d70cba6484dd95ba3b59395ecfcba31ad/webpack.config.js#L37-L48):
  ```js
      babel: {
        presets: [
            ['@babel/preset-env', {
                modules: false,
                // This adds polyfills when needed. Requires core-js dependency.
                // See https://babeljs.io/docs/en/babel-preset-env#usebuiltins
                // Note that you still need to add custom polyfills if necessary (e.g. whatwg-fetch)
                useBuiltIns: 'usage',
                corejs: 3
            }]
        ],
    }
  ```
- [webpack.config.js module.exports target](https://github.com/Freymaurer/SAFE-MinExcel/blob/b87b597d70cba6484dd95ba3b59395ecfcba31ad/webpack.config.js#L84):
  ```js
    target: ["web", "es5"],
  ```
- [webpack.config.js module.exports module rules](https://github.com/Freymaurer/SAFE-MinExcel/blob/b87b597d70cba6484dd95ba3b59395ecfcba31ad/webpack.config.js#L141-L148):
  ```js
    module: {
        rules: [
            {
                test: /\.m?js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: CONFIG.babel
                },
            },
            ...
  ```

**Comment by Freymaurer** [comment]
While working with webpack 5 and the changes shown above i noticed that hot module replacement is broken. I checked the error message and found the following [post](https://stackoverflow.com/questions/65640449/how-to-solve-chunkloaderror-loading-hot-update-chunk-second-app-failed-in-webpa) referring to this [comment](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/88#issuecomment-627558799).

So by expanding `optimization` with `runtimeChunk: "single"` it works again.

```js
// more context
module.exports = {
    // ..
    optimization: {
        splitChunks: {
            chunks: 'all'
        },
        runtimeChunk: "single"
    },
    // ..
}
```

**Comment by isaacabraham** [comment]
@Freymaurer Is this still an issue you're seeing (i.e. requirement) given that it's not even supported by Microsoft any longer?

**Comment by Freymaurer** [comment]
I understand this is an edge case. I used this for an excel add-in. Excel 2019 still uses ie11 as in app browser.

**Comment by martinbryant** [comment]
Closing this as end of life of Internet Explorer was 15 June 2022 - https://www.microsoft.com/en-US/download/details.aspx?id=41628
