### ISSUE TITLE
Mistake in Client tests recipe?

### ISSUE THREAD

**Issue by Freymaurer** [SAFE-Stack/docs#251]
Hello!

I am pretty sure [this](https://github.com/SAFE-Stack/docs/blob/3c7d0087a740b182ebda91a8e1653751ce638ad7/docs/recipes/developing-and-testing/testing-the-client.md?plain=1#L54):

```powershell
dotnet add src/Client.Tests reference src/Client
```

Should be:

```powershell
dotnet add tests/Client reference src/Client
```

**Comment by teknikal-wizard** [comment]
Well spotted, I've opened a PR to fix https://github.com/SAFE-Stack/docs/pull/262
