### ISSUE TITLE
Azure Type Provider warning may be outdated

### ISSUE THREAD

**Issue by sonicbhoc** [SAFE-Stack/docs#252]
On this page:
https://safe-stack.github.io/docs/component-azure/

Near the bottom, the following warning is issued:

`Many of the above services have ready-made SDKs that can be run on .NET and therefore from F#. In addition, the [Azure Storage Type Provider](http://fsprojects.github.io/AzureStorageTypeProvider/) provides unparallel ease of access to Azure Storage Blobs, Queues and Tables from F# (currently not yet supported on .NET Core).`

The nuget package now supports `.netstandard2.0`, which can be consumed by ASP.NET Core projects. Is there any functionality that doesn't work under .NET Core?

Also, `unparallel` should be `unparalleled.`

**Comment by isaacabraham** [comment]
@sonicbhoc It *should* work but to be honest the project is now more-or-less sunsetted. I think we should just remove a reference to it.

**Comment by mattgallagher92** [comment]
Removed in https://github.com/SAFE-Stack/docs/commit/4769d8f01a8b8d4c0dc5111c756fcc77ce228df6.
