### ISSUE TITLE
upload-file-from-client instructions fail

### ISSUE THREAD

**Issue by johanvts** [SAFE-Stack/docs#261]
I'm trying to follow the instructions here: https://safe-stack.github.io/docs/recipes/client-server/upload-file-from-client/
However when I get to 
```
    Bulma.fileInput [
                prop.onChange (handleFileEvent onLoad)
            ]
 ```
 I'm told `prop` "is not defined". I have had no luck finding out why. https://dzoukr.github.io/Feliz.Bulma/#/documentation/form doesn't seem to document the ~File~ namespace at all.
 
 Thank you in advance for all help.

**Comment by Zaid-Ajaj** [comment]
can you try `Feliz.prop.onChange`? to fully qualify the namespace

**Comment by johanvts** [comment]
Yes, this resolved the issue. Thank you.
