### ISSUE TITLE
Move to GH Actions?

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#269]
@theimowski could you give me admin permissions on the Travis CI as the GH token has expired and needs refreshing?

In the medium term, we can probably ditch Travis and just move onto GH Actions directly, right?

**Comment by isaacabraham** [comment]
I've fixed the build now with a new token.

**Comment by theimowski** [comment]
Is this sorted now? I haven't used GitHub actions before but if it's easy to set up then a move would be a wise step - Travis seems to cause some issues here and there

**Comment by theimowski** [comment]
I've added a basic GitHub action that pushes to gh-pages, seems to work fine https://github.com/SAFE-Stack/docs/actions/runs/3974214318

also removed the travis.yaml config

**Comment by mattgallagher92** [comment]
Thanks Tomasz! Not sure what's going on with the extra action either. Seems to be working fine but I'd have more confidence if somebody investigated to make sure that we're not going to get any interference. Will leave open for now until somebody has checked that out.

**Comment by jwthomson** [comment]
Based on the [discussion I found on StackOverflow](https://stackoverflow.com/questions/72079903) when looking into this, it seems like it is nothing to worry about.

On my fork I went into `Repo Settings > Pages`, then set `Source` to "Github Actions" and the extra action didn't appear.
