### ISSUE TITLE
Fable Forms questions / optimisations

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#276]
* Could we use Femto for adding packages?
* Why do we need to move to NPM package for Bulma (this is just my lack of knowledge)?
* Source files and assets e.g. `./src/Client/styles.scss` etc. should probably be quoted to show as code rather than plain text.
* It would be good to have a tiny bit of explanation as to why we're doing what we're doing.
* This bit is confusing: "Update ./webpack.config.js to use the new stylesheet, per the [SAFE Stack recipe](https://safe-stack.github.io/docs/recipes/ui/add-style/). Add a cssEntry property to CONFIG:". Does it mean to *first* follow the recipe and *then* add a `cssEntry` property? Or that the instruction to add the `cssEntry` is taken from that recipe?
* "Bind a Fable.Form value to form" - The meaning here is unclear. Are we modifying something existing or creating a new thing? What's it for?
* "Replace the Bulma TODO field with a Fable.Form html view:" This is unclear - better to say what the actual node to replace is.
* `ValidateOnSubmit` should probably be `ValidateOnBlur`?
* The filename is incorrect for `style.scss` - it is shown in one place as `styles.scss` (note the extra 's').

**Comment by mattgallagher92** [comment]
This relates to [the recipe](https://safe-stack.github.io/docs/recipes/client-server/fable.forms/).
