### ISSUE TITLE
Explain dev and prod environments

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#28]
It's not easily clear how to go from dev to prod with SAFE apps - in dev you normally use `webpack-dev-server` to host the client but at deployment time you pre-compile the js and host in either the server as static content or some other way e.g. blob storage, function etc..

**Comment by forki** [comment]
Yes. Very important point.

**Comment by kunjee17** [comment]
@isaacabraham I am using release settings from SAFE to deploy to prod. Does it required any other things. I know there can be many pre-run stuff. But basics still works. 

One things I did, was that I need to manage port for Azure docker. As by default it is port 8080. So, that I am doing using dotnet core settings for environment. I m also setting up ASPNETCORE_ENVIRONMENT variable on my machine to keep the dev and stag and prod separate.

All these details are useful ?

**Comment by isaacabraham** [comment]
This has been documented.
