### ISSUE TITLE
SAFE v5 updates

### ISSUE THREAD

**Issue by theprash** [SAFE-Stack/docs#290]
This issue tracks all of the docs updates needed for SAFE v5. The changes should go live along with v5 of the template: https://github.com/SAFE-Stack/SAFE-template/issues/569

**Make separate PRs for each change (or small set of changes) as required.**

- [x] Update non-recipe docs

- [x] Remove v2 legacy recipes

- [x] Move existing recipes to v4 legacy section

- [x] Create v5 recipes (take from v4, update if needed, or remove if obsolete)
  - [x] Upgrade from v4 to v5 (test out on SAFE template and SAFE search 3?)
  - [x] Upgrade from v2 to v3
  - [x] Upgrade from v3 to v4
  - [x] Create a new Recipe
  - [x] Build
    - [x] Add build automation
    - [x] Remove FAKE
    - [x] Package my SAFE app for deployment
    - [x] Create a docker image
  - [x] Dev / Test
    - [x] Test the Client
    - [x] Test the Server
    - [x] Debug a SAFE app
    - [x] Use hot reload (DELETED, comes for free with vite)
  - [x] Client / Server
    - [x] Add support for Fable Remoting
    - [x] Perform roundtrips with MVU
    - [x] Get data from the server
    - [x] Post data to the server
    - [x] Handle server errors on the client
    - [x] Share code between the client and the server
    - [x] Use Giraffe instead of Saturn
    - [x] Upload file from the client
    - [x] Serve a file from the back-end
    - [x] Add support for Fable.Forms
  - [x] Data
    - [x] Quickly add a database
    - [x] Create a data module using SQLProvider SQL Server SSDT
  - [x] UI
    - [x] Add FontAwesome support
    - [x] Add Stylesheet support
    - [x] Add Bulma support (DELETED)
    - [x] Use different Bulma Themes (DELETED)
    - [x] Remove Bulma (DELETED)
    - [x] Add Tailwind support
    - [x] Add daisyUI support
    - [x] Add Feliz support
    - [x] Migrate from a CDN stylesheet to an NPM package
    - [x] Add routing with state shared between pages
    - [x] Add routing with separate models per page
    - [x] Add Routing with UseElmish
  - [x] Javascript
    - [x] Import a JavaScript module
    - [x] Add Support for a Third Party React Library
  - [x] Package Management
    - [x] Add an NPM package to the Client
    - [x] Add a NuGet package to the Server
    - [x] Add a Nuget package to the Client
    - [x] Migrate to Paket from NuGet
    - [x] Migrate to NuGet from Paket
    - [x] Sync NuGet and NPM Packages

**Comment by Larocceau** [comment]
should we create a branch for this to merge work into? I think it would be nice to be able to merge into this without getting things to master before we release the new version of the template

**Comment by theprash** [comment]
@Larocceau Yes, good idea. I've just made v5-docs

**Comment by isaacabraham** [comment]
How does the "Remove Bulma" recipe look? Surely it's obsolete now (as is the Add Tailwind?)? Instead we should have a Remove Tailwind (and perhaps an Add Bulma)?

**Comment by isaacabraham** [comment]
Also we should be removing anything v2 / v3 from the repo. v4-specific stuff should be archived into the Legacy Template docs folder or simply removed.

**Comment by theprash** [comment]
All of the updates are deployed now 🥳✔️
