### ISSUE TITLE
Create a "zero to SAFE" recipe

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#294]
A few people have asked about something like this: something that starts from a clean repository and builds a SAFE Stack app. Doing this would remove much of the magic + FUD around SAFE, if it was done in a clear step-by-step manner.

It wouldn't necessarily need to add everything e.g. perhaps Tailwind is too opinionated - but having a basic client and server with Feliz, the Elmish loop and Fable Remoting + Saturn would be totally fine.

**Comment by Larocceau** [comment]
@isaacabraham I saw you wrote this. Can the issue be closed?

**Comment by theprash** [comment]
@isaacabraham @Larocceau Looks like it's done [here](https://safe-stack.github.io/docs/safe-from-scratch/) so I'll close this.
