### ISSUE TITLE
Events page 

### ISSUE THREAD

**Issue by RicoSaupe** [SAFE-Stack/docs#308]
Is the events page something we continue to fill. Currently its pretty much empty. Are there any new events coming up?

**Comment by isaacabraham** [comment]
I think we should remove it - it doesn't get updated regularly enough to be honest.

**Comment by isaacabraham** [comment]
Feedback welcome from anyone - if I don't hear back by this time next week, we'll delete it

**Comment by RicoSaupe** [comment]
since you removed it, let me close it.
