### ISSUE TITLE
404 overview code sharing

### ISSUE THREAD

**Issue by Zaid-Ajaj** [SAFE-Stack/docs#32]
![export](https://user-images.githubusercontent.com/13316248/39220686-ebc273c4-4832-11e8-9de4-63eb7749f96c.png)

![screenshot from 2018-04-25 02-46-35](https://user-images.githubusercontent.com/13316248/39220694-f63fcaae-4832-11e8-9ef5-75ea2cb58656.png)

**Comment by forki** [comment]
Any chance you can send us a pull request?

Zaid Ajaj <notifications@github.com> schrieb am Mi., 25. Apr. 2018, 02:47:
