### ISSUE TITLE
Bug in Saturn to Giraffe guide

### ISSUE THREAD

**Issue by jwthomson** [SAFE-Stack/docs#362]
Someone on the F# discord mentioned that the guide for switching from Saturn to Giraffe did not work for them.

Repro steps:
  1. Create SAFE app
  2. Follow the guide (https://safe-stack.github.io/docs/recipes/client-server/saturn-to-giraffe/)
  3. Run the bundled version of the app:
  ```powershell
      dotnet run Bundle
      cd deploy
      Server.exe
  ```

Expectation:
Hit `localhost:5000` in your browser and see the default todo app.

Actual result:
Hit `localhost:5000` in your browser and get a 404 error.

The fact that the application does work in dev mode `dotnet run` but fails once bundled - indicates to me that there is an an inconsistency with the way Vite handles incoming requests vs how Kestrel/IIS handles incoming requests.

I think the difference in behaviour is due to Kestrel is not remapping root requests to `index.html` by default. In contrast, Vite defaults to serving `index.html` for root requests. (and this seems to be non-negotiable! https://vitejs.dev/guide/#index-html-and-project-root)

For me, the workaround posted in Discord - renaming the `public` folder to `wwwroot` - did not work.

Working on a PR to fix.

**Comment by astrobytez** [comment]
That was me on Discord. Thanks for putting this together! :)

**Comment by Larocceau** [comment]
@jwthomson can this be closed?

**Comment by jwthomson** [comment]
@Larocceau yes 😄
