### ISSUE TITLE
Quickstart instructions break on virgin machine with .NET 9 present

### ISSUE THREAD

**Issue by OutOfScopeia** [SAFE-Stack/docs#368]
It seems .NET 9 has changed some dotnet CLI syntax. This is what I get on a machine that has .NET 9 on it but it never had the SAFE Template on it:
![image](https://github.com/user-attachments/assets/6bc0b3d1-6d5b-4546-b120-ae0ad8924577)

Technically, the quickstart lists .NET 8 as a pre-requisite, but the above happens if someone has both 8 and 9 on their system, which will become a more and more viable scenario as time goes on.

Current workaround:
- have a NET8-locking **global.json** present in the current folder before running **dotnet new install SAFE.Template**,
- install the template,
- either delete the **global.json** before running **dotnet new SAFE** or do **dotnet new SAFE --force** instead.

**Comment by isaacabraham** [comment]
Hmmm. I have .NET 9 installed and this doesn't happen for me.

**Comment by Larocceau** [comment]
I don't see this behaviour either

**Comment by Larocceau** [comment]
@OutOfScopeia confirmed that this issue does not actually arise for him anymore
