### ISSUE TITLE
Documentation about azure functions 

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/docs#40]

**Comment by isaacabraham** [comment]
What do we need to document here? I'm not a fan in the idea of replacing Functions documentation for F# etc. on the Azure site. Perhaps just something architectural in terms of how it can fit in with a SAFE web app or what?

**Comment by forki** [comment]
No. Not replacing. Just giving small intro that it works nicely and where
to find more information

Isaac Abraham <notifications@github.com> schrieb am So., 6. Mai 2018, 13:19:

**Comment by isaacabraham** [comment]
Deployed the docs from #55.
