### ISSUE TITLE
Clarify stance on Suave

### ISSUE THREAD

**Issue by wallymathieu** [SAFE-Stack/docs#52]
Right now the docs says that there is an issue with the Suave license. From what I can gather from the discussion at https://github.com/SuaveIO/suave/issues/704 it seems like there is no Suave licensing issue but rather something else. Perhaps writing that SAFE stack is [focusing on .net core](https://github.com/SuaveIO/suave/issues/704#issuecomment-401002212) in order to not cause undue confusion.

**Comment by isaacabraham** [comment]
@wallymathieu I'm closing this issue - I think it's been discussed at length on a couple of other repos. Feel free to DM me personally (or anyone else on the SAFE team) if you'd like though.

**Comment by wallymathieu** [comment]
The issue isn't really resolved due to the fact that https://github.com/SAFE-Stack/docs/blob/master/docs/news.md says that there is unclear future of the licensing of Suave. I thought that was resolved in the issue on https://github.com/SuaveIO/suave/issues/704 ?

**Comment by isaacabraham** [comment]
@wallymathieu I don't understand. In your post in the Suave repo (IIRC) you said that you understood and were happy to close the issue?

**Comment by wallymathieu** [comment]
Yes, as far as I understood it there isn't any future license changes for Suave, so it's not an issue for the Suave repo. What I understood from the issue was that the SAFE stack team has decided to go with Saturn, Giraffe and asp.net core. Initially it looks like there was confusion around the licensing of Suave. Though in the end since Saturn and Giraffe are built to depend heavily on asp.net core, I guess that part of the decision is to stay aligned with the asp.net core performance improvements?

**Comment by isaacabraham** [comment]
Rather "built to take advantage" than "built to depend" :-)

We simply don't feel that Suave fits with the SAFE strategy going forward (and now that the license issue has been cleared up, I've published a new news item that makes that clear).

This isn't a criticism of them; their team simply are simply going in a different direction to ours, and it doesn't make sense for us to continue to recommend or support it in SAFE any longer.

I genuinely hope that clarifies it for you but if you want to discuss more, feel free to reach out to me or one of the other people privately.

**Comment by wallymathieu** [comment]
Nice! I think that clears it up!
