### ISSUE TITLE
Document Elmish Bridge

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#56]
Explain what it is and where it can be used.

**Comment by isaacabraham** [comment]
@Zaid-Ajaj would you be interested in writing something up about this for incorporation onto the SAFE site? If not, I can have a crack at it, but would you be able to review it?

**Comment by Zaid-Ajaj** [comment]
Ofcourse I would be interested. I will be able write it soon-ish, then maybe @Nhowka can review it for correctness.

**Comment by isaacabraham** [comment]
Doh. Apologies - I meant to initially tag @Nhowka to ask (as the author of the repository) to document it. Please accept my apologies for that. @Nhowka - would you be interested in writing something up or happy for Zaid to have a go and review?

**Comment by isaacabraham** [comment]
@Nhowka @Zaid-Ajaj i've merged this in, made a few small changes and pushed. Thanks a lot for this! Also - please check out the [client server](https://safe-stack.github.io/docs/feature-clientserver/) page which now adds Elmish Bridge into the table - happy to put any corrections in. Thanks!

**Comment by Zaid-Ajaj** [comment]
Thanks @isaacabraham, I have read the section and looks good. 

On a side-note, the bits on Fable.Remoting are outdated, I will send a PR soon-ish when time permits ;)

**Comment by isaacabraham** [comment]
@Zaid-Ajaj that would be very much appreciated :-)
