### ISSUE TITLE
Broken link on introduction page

### ISSUE THREAD

**Issue by slifin** [SAFE-Stack/docs#68]
Clicking "next quick start" at the bottom of https://safe-stack.github.io/docs/intro/ 

Takes you to: https://safe-stack.github.io/docs/intro/quickstart/ which 404s instead of:
https://safe-stack.github.io/docs/quickstart/

**Comment by slifin** [comment]
Seems to be the case for a lot of these links, the arrow buttons often cause 404

**Comment by isaacabraham** [comment]
Fixed. Not sure why that happened but I've just re-deployed, all is working again.

**Comment by isaacabraham** [comment]
Thanks for pointing it out though!
