### ISSUE TITLE
Further simplify installation

### ISSUE THREAD

**Issue by slifin** [SAFE-Stack/docs#69]
I apologise in advance this is probably the wrong repo for this suggestion

Is it possible to install the prerequisites with a package like:

choco install dotnetsafe
brew install dotnetsafe
apt install dotnetsafe

Feels like we could lower the first barrier to entry by doing so

**Comment by isaacabraham** [comment]
I'm not against this idea - or at least seeing if there's a way we could streamline this further (this might also help with people have different versions of yarn / node? or perhaps not - can they be installed side-by-side?)

**Comment by isaacabraham** [comment]
Closing - SAFE 2, along with core 3.1 local tools, simplifies this I think.
