### ISSUE TITLE
SAFE doc site: navigation bar at the bottom of each page lead to 404 Not Found.

### ISSUE THREAD

**Issue by fabiogaragiola** [SAFE-Stack/docs#72]
https://safe-stack.github.io/docs/

The navigation bar at the bottom of each page is broken: arrow links always lead to a 404 Not Found page except when navigating from Home to Introduction.

**Comment by isaacabraham** [comment]
This was fixed a few weeks ago - looks like it's back again! Not sure what's going on here.

**Comment by theimowski** [comment]
hmm, might be me occasionally deploying the docs from my box?
