### ISSUE TITLE
Links still broken

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#75]
I've temporarily disabled footer links until we fix this. cc: @theimowski

**Comment by isaacabraham** [comment]
@theimowski I've just pushed again to the live site, it now seems to be "ok". Can you double check?

**Comment by theimowski** [comment]
It works for me both on the website and local `mkdocs serve`

**Comment by isaacabraham** [comment]
So then it's working now - I had to specify using abs_url in the theme. I don't know why.
