### ISSUE TITLE
Client / Server Communication

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/docs#81]
This is now outdated as of the latest SAFE template which uses Fable 2 and Thoth. I'm not even sure what the "correct" way to do this is.

1. What should we replace the sample calls with `fetchAs` in [the docs](https://safe-stack.github.io/docs/feature-clientserver/) with?
2. What needs changing on the server side? I assume that the section **Turning on Fable's JSON Converter** is now outdated and should be changed to use Thoth as well?
3. What are the options, pros / cons, when should you use "full" Thoth or Auto decoding etc.?

cc: @mangelmaxime @theimowski @Krzysztof-Cieslak @alfonsogarciacaro.

**Comment by MangelMaxime** [comment]
>     1. What should we replace the sample calls with `fetchAs` in [the docs](https://safe-stack.github.io/docs/feature-clientserver/) with?

```fs
// Cache the customer decoder for size optimisation
// See: https://mangelmaxime.github.io/Thoth/json/v2/decode.html#size-optimization
let customerDecoder = Decode.Auto.generateDecoder<Customer>()

promise {    
    let! customers = Fetch.fetchAs (sprintf "api/customers") (Decode.array customerDecoder) []
    // do more with customers here...
}
```

>   2\. What needs changing on the server side? I assume that the section **Turning on Fable's JSON Converter** is now outdated and should be changed to use Thoth as well?

If you want to use the auto decoders in a transparent way from Giraffe then users should use `ThothSerializer`.

If they want to use manual decoders or if needed, they can read/write the string directly from/into the body. [Example](https://github.com/SAFE-Stack/SAFE-BookStore/pull/367/files#diff-231fb1aacd4e4f793fcdc2352b9e4ac5)

[For example](https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Server/Program.fs#L46-L47)

>     3\. What are the options, pros / cons, when should you use "full" Thoth or Auto decoding etc.?

This part can be opiniated but in IHMO:

If you are sharing your F# types, then you can use auto decoders/encoders with the limitation that you can't auto encode/decode classes.

```fs
// This will return None (if you set the json `MaybeClass` to `null` in the json)
type RecordWithOptionalClass =
    { MaybeClass : BaseClass option
      Must : string }

// This will return an Error
type RecordWithRequiredClass =
    { Class : BaseClass
      Must : string }
```

Use manual decoders/encoders if:
- You want control the JSON representation
- Are calling an external services
- Are using F# on one side and anothers languages on the other side

**Comment by MangelMaxime** [comment]
Yes it's coming from `Thoth.Json.Giraffe`

> Is there a more lightweight way

For now no because with Fable 2 you need to use `[<Inject>] ?resolver: ITypeResolver<'T>` for Fable to include the `TypeInfo` in the runtime.

And `Fable.PowerPack.Fetch` is function based. 
We designed the `Fable.PowerPack.Fetch` so have the experience when using manual or auto decoders. But if you have a suggestion to support both style in a clean way we can discuss it on the PowerPack repo.

**Comment by isaacabraham** [comment]
I only thought there was another way because the comment says "cache the decoded for size optimization " - is there another way without caching e.g. is this valid?

```fsharp
let customerDecoder = Decode.Auto.generateDecoder<Customer>()

promise {    
    let! customers = Fetch.fetchAs (sprintf "api/customers") (Decode.Auto.generateDecoder<Customer []> []
    // do more with customers here...
}
```

**Comment by MangelMaxime** [comment]
Ah yes, it's valid.

**Comment by MangelMaxime** [comment]
I didn't know about the last one. 

And I didn't experiment a lot with the auto decoder but it's really nice to see. I personnaly prefer if we show an usage with type hints, because I think it's better to be sure of the return type :)

So in the doc we could show something like::

```fs
let! customers = fetchAs<Customers []> "/api/customers" (Decode.Auto.generateDecoder())

// or
let! customers : Customers [] = fetchAs "/api/customers" (Decode.Auto.generateDecoder())
```

In more complexe example showing the last case can be something interesting. Because from my experience, you end up rewriting the `fetch` module to make your helpers dedicated to your app. 

For example, because I want to support the `refreshToken` feature in my production I have helpers like:
```fs
    let postRecord (url: string) (user : User) (body: string) (properties: RequestProperties list) =
        let httpRequest token =
            let defaultProps =
              [ RequestProperties.Method HttpMethod.POST
                requestHeaders [ ContentType "application/json"
                                 Authorization ("Bearer " + token) ]
                RequestProperties.Body !^(body) ]

            List.append defaultProps properties
            |> fetch url

        httpRequest user.Token
        |> Promise.bind (handleRefreshToken user httpRequest)
```

So we can imagine the same applied to get `quickFetch` synthax.

**Comment by isaacabraham** [comment]
Great, I agree. I'll look to push some updates to the docs this week - if you could review it when it's ready that would be great. @theimowski I'm also preparing a PR to update the template to move over to Thoth completely.

**Comment by MangelMaxime** [comment]
Sure ping me when I need to review it.

**Comment by isaacabraham** [comment]
The PR in the template is available [here](https://github.com/SAFE-Stack/SAFE-template/pull/179). Docs to follow.

**Comment by theimowski** [comment]
I'm wondering whether it makes sense to add an example of `fetch` with custom Record type instead of an integer?
