### ISSUE TITLE
Configure auto deployment for master branch

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/docs#98]
Would be nice if pushing to master triggered automatic deployment to gh-pages

**Comment by isaacabraham** [comment]
OK - what would be involved in doing this anyone? @Krzysztof-Cieslak ideas?

**Comment by Krzysztof-Cieslak** [comment]
This could be easily solved with GitHub Actions, unfortunately, I only have enabled preview on my personal account, not on org one.

**Comment by theimowski** [comment]
Here's a solution using Travis CI: http://derekweitzel.com/2017/02/08/deploying-docs-on-github-with-travisci/

For GitHub Actions I've found https://github.com/marketplace/actions/mkdocs-build-and-deploy-to-github-pages

I'm happy to do this - which option do we prefer?

**Comment by isaacabraham** [comment]
github seems logical seem here is where the code is also stored?

**Comment by theimowski** [comment]
Ok i registered for the GitHub Actions preview. @Krzysztof-Cieslak  it seems you can choose only a personal account in registration, no organisations. Hence I assume one can use it from personal account for organisation projects also

**Comment by Krzysztof-Cieslak** [comment]
> Hence I assume one can use it from personal account for organisation projects also

Nope, you can't. Or at least I don't see such an option

**Comment by theimowski** [comment]
Ok then it might suggest GitHub Actions preview is only for personal repositories, since I didn't get "SAFE-Stack" in the dropdown. 
I shall give the Travis option a try in this case
